kind = "DojoContract"
class_hash = "0x5e7f1e46643cdbfa6b957f47db65c30e3b1dbf28235373ff1981b9fd343d157"
original_class_hash = "0x5e7f1e46643cdbfa6b957f47db65c30e3b1dbf28235373ff1981b9fd343d157"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shogun_systems_battle_battle.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::battle::battle"
