kind = "DojoContract"
class_hash = "0x5c7663294254987139dd5671ef46a814539e2cc3af8d390fe40c3261bfee246"
original_class_hash = "0x5c7663294254987139dd5671ef46a814539e2cc3af8d390fe40c3261bfee246"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shogun_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::actions::actions"
