kind = "DojoContract"
class_hash = "0x78297086c18486bdbad7c6fdf7ac713c78a513ad0231942dcd2bdae91db33d6"
original_class_hash = "0x78297086c18486bdbad7c6fdf7ac713c78a513ad0231942dcd2bdae91db33d6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shogun_systems_battle_battle.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::battle::battle"
