kind = "DojoContract"
class_hash = "0x7cb6e80e221908307864de2d7c91a8853a23240de9d1379e4a71003a0452ee1"
original_class_hash = "0x7cb6e80e221908307864de2d7c91a8853a23240de9d1379e4a71003a0452ee1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shogun_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::admin::admin"
