kind = "DojoContract"
class_hash = "0x37cb4ec35611a3ec27b6b42c784b673c54188c50070ed204ed00774e3cdebf9"
original_class_hash = "0x37cb4ec35611a3ec27b6b42c784b673c54188c50070ed204ed00774e3cdebf9"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/shogun_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::actions::actions"
