export const itemData: { [key: string]: { width: number, height: number } } = {
  item1: { width: 2, height: 2 },
  item2: { width: 1, height: 2 },
  item3: { width: 3, height: 1 },
  item4: { width: 1, height: 1 },
  item5: { width: 2, height: 1 },
  item6: { width: 1, height: 3 },
  item7: { width: 3, height: 3 },
  item8: { width: 2, height: 3 },
  item9: { width: 1, height: 1 },
  item10: { width: 2, height: 2 },
  item11: { width: 1, height: 2 },
  item12: { width: 3, height: 1 },
  item13: { width: 1, height: 1 },
  item14: { width: 2, height: 1 },
  item15: { width: 1, height: 3 },
  item16: { width: 3, height: 3 },
  item17: { width: 2, height: 3 },
  item18: { width: 1, height: 1 },
  item19: { width: 2, height: 2 },
  item20: { width: 1, height: 2 },
};
