kind = "DojoModel"
class_hash = "0x43724e132374756a45596836ab3ecd52a57f292d2098dc8bfcf791fb2aefc4b"
original_class_hash = "0x43724e132374756a45596836ab3ecd52a57f292d2098dc8bfcf791fb2aefc4b"
abi = "manifests/dev/abis/base/models/shogun_models_battleLog_battle_log_detail.json"
name = "shogun::models::battleLog::battle_log_detail"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "battleLogId"
type = "usize"
key = true

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "whoTriggered"
type = "felt252"
key = false

[[members]]
name = "whichItem"
type = "usize"
key = false

[[members]]
name = "damageCaused"
type = "usize"
key = false

[[members]]
name = "isDodged"
type = "bool"
key = false

[[members]]
name = "buffType"
type = "felt252"
key = false

[[members]]
name = "regenHP"
type = "usize"
key = false

[[members]]
name = "player_armor_stacks"
type = "usize"
key = false

[[members]]
name = "player_regen_stacks"
type = "usize"
key = false

[[members]]
name = "player_reflect_stacks"
type = "usize"
key = false

[[members]]
name = "player_spike_stacks"
type = "usize"
key = false

[[members]]
name = "dummy_armor_stacks"
type = "usize"
key = false

[[members]]
name = "dummy_regen_stacks"
type = "usize"
key = false

[[members]]
name = "dummy_reflect_stacks"
type = "usize"
key = false

[[members]]
name = "dummy_spike_stacks"
type = "usize"
key = false
