kind = "DojoModel"
class_hash = "0x76a41947eaca241ed0b411a058ad01f5e218bee1246d106f412a0e89c8316b8"
original_class_hash = "0x76a41947eaca241ed0b411a058ad01f5e218bee1246d106f412a0e89c8316b8"
abi = "manifests/dev/abis/base/models/shogun_models_battleLog_battle_log_detail_counter.json"
name = "shogun::models::battleLog::battle_log_detail_counter"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "battleLogId"
type = "usize"
key = true

[[members]]
name = "count"
type = "usize"
key = false
