kind = "DojoModel"
class_hash = "0x22e5af7e15be3be04e4fb97d7feb758158846c379ff41efc20d10fc71a26313"
original_class_hash = "0x22e5af7e15be3be04e4fb97d7feb758158846c379ff41efc20d10fc71a26313"
abi = "manifests/dev/abis/base/models/shogun_models_item_items_counter.json"
name = "shogun::models::item::items_counter"

[[members]]
name = "id"
type = "felt252"
key = true

[[members]]
name = "count"
type = "usize"
key = false
