kind = "DojoModel"
class_hash = "0x3029f8f9321078fd3a43a722a86136dd88d020408299e04149a61cce42fdec7"
original_class_hash = "0x3029f8f9321078fd3a43a722a86136dd88d020408299e04149a61cce42fdec7"
abi = "manifests/dev/abis/base/models/shogun_models_dummyCharacter_dummy_character_counter.json"
name = "shogun::models::dummyCharacter::dummy_character_counter"

[[members]]
name = "level"
type = "usize"
key = true

[[members]]
name = "count"
type = "usize"
key = false
