kind = "DojoModel"
class_hash = "0x195f0d1b3ff1d7e8bc2d325aa96084a981de6f168b5aac9ad460847706d2854"
original_class_hash = "0x195f0d1b3ff1d7e8bc2d325aa96084a981de6f168b5aac9ad460847706d2854"
abi = "manifests/slot/abis/base/models/shogun_models_characterItem_character_item_storage.json"
name = "shogun::models::characterItem::character_item_storage"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "id"
type = "usize"
key = true

[[members]]
name = "itemId"
type = "usize"
key = false
