kind = "DojoModel"
class_hash = "0x59f62473957b80b2fd7831f922c93cd9896ba6825c5a2650c6596ada6a86d3a"
original_class_hash = "0x59f62473957b80b2fd7831f922c93cd9896ba6825c5a2650c6596ada6a86d3a"
abi = "manifests/slot/abis/base/models/shogun_models_shop_shop.json"
name = "shogun::models::shop::shop"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "item1"
type = "usize"
key = false

[[members]]
name = "item2"
type = "usize"
key = false

[[members]]
name = "item3"
type = "usize"
key = false

[[members]]
name = "item4"
type = "usize"
key = false

[[members]]
name = "item5"
type = "usize"
key = false

[[members]]
name = "item6"
type = "usize"
key = false
