kind = "DojoModel"
class_hash = "0x499636994d01c6a4cb67ab28663c816f6d12e36f58c7d8cdd633a1419e29c99"
original_class_hash = "0x499636994d01c6a4cb67ab28663c816f6d12e36f58c7d8cdd633a1419e29c99"
abi = "manifests/slot/abis/base/models/shogun_models_character_character.json"
name = "shogun::models::character::character"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "felt252"
key = false

[[members]]
name = "gold"
type = "usize"
key = false

[[members]]
name = "health"
type = "usize"
key = false

[[members]]
name = "wins"
type = "usize"
key = false

[[members]]
name = "loss"
type = "usize"
key = false

[[members]]
name = "dummied"
type = "bool"
key = false

[[members]]
name = "rating"
type = "usize"
key = false

[[members]]
name = "totalWins"
type = "usize"
key = false

[[members]]
name = "totalLoss"
type = "usize"
key = false

[[members]]
name = "winStreak"
type = "usize"
key = false

[[members]]
name = "birthCount"
type = "u32"
key = false

[[members]]
name = "updatedAt"
type = "u64"
key = false
