kind = "DojoModel"
class_hash = "0x27c18cb7a95624d10e7aa1210cb47ace497e94ead00f5af387a048d5ddbb7ed"
original_class_hash = "0x27c18cb7a95624d10e7aa1210cb47ace497e94ead00f5af387a048d5ddbb7ed"
abi = "manifests/slot/abis/base/models/shogun_models_dummyCharacterItem_dummy_character_item.json"
name = "shogun::models::dummyCharacterItem::dummy_character_item"

[[members]]
name = "level"
type = "usize"
key = true

[[members]]
name = "dummyCharId"
type = "u32"
key = true

[[members]]
name = "counterId"
type = "usize"
key = true

[[members]]
name = "itemId"
type = "usize"
key = false

[[members]]
name = "position"
type = "Position"
key = false

[[members]]
name = "rotation"
type = "usize"
key = false
