kind = "DojoContract"
class_hash = "0x66956b68fe8a901c30b57635738c4c9ffd86234b527a0422e91f1225370b7a4"
original_class_hash = "0x66956b68fe8a901c30b57635738c4c9ffd86234b527a0422e91f1225370b7a4"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/shogun_systems_battle_battle.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::battle::battle"
