kind = "DojoContract"
class_hash = "0x7c297933a1d39c5130aacf63d2e5e1202edc19947e7b8ddb134c05f4e6b8af6"
original_class_hash = "0x7c297933a1d39c5130aacf63d2e5e1202edc19947e7b8ddb134c05f4e6b8af6"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/shogun_systems_admin_admin.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::admin::admin"
