kind = "DojoContract"
class_hash = "0x5f818c0759105e8bfa8300d8de3f25927d220583c1c8f299384293db0c19607"
original_class_hash = "0x5f818c0759105e8bfa8300d8de3f25927d220583c1c8f299384293db0c19607"
base_class_hash = "0x0"
abi = "manifests/slot/abis/base/contracts/shogun_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "shogun::systems::actions::actions"
